name: Publish Docker image to Docker Hub and Github

on:
  # push:
  #   branches: [ main ]
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - download_arch: x86_64
            platforms: linux/amd64
          - download_arch: aarch64
            platforms: linux/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platforms }}
          buildargs: ARCH=${{matrix.buildargs }}
          push: true
          tags: spuder/openscad:latest